"""Synthetic contextual replay environment.

Replay data are generated by a behaviour (logging) policy pi_b acting in a
contextual decision problem with p covariates and K discrete actions:

    X ~ N(0, Sigma)                      (clean contexts)
    A | X ~ pi_b(. | X)  (softmax of nonlinear logits g_a(X))
    Y = mu_A(X) + eps                    (eps from one of several noise laws)

The ESTIMAND is always the value of the target policy in the CLEAN
environment:  V(pi) = E_{X ~ N(0,Sigma)} [ sum_a pi(a|X) mu_a(X) ].
All noise laws used for the main scenarios are symmetric around 0, so for
them the clean value equals the value of the observed (noisy) reward. For the
covariate-contamination scenario a fraction of replay rows come from a
different (high-leverage) context distribution; those rows are treated as
anomalous trajectories and the estimand remains the clean-population value
(Huber-contamination framing).
"""
from __future__ import annotations

from dataclasses import dataclass, field
import numpy as np

P = 10  # covariates
K = 4   # actions


# Fixed structural parameters (drawn once from a fixed seed, never re-drawn)

_param_rng = np.random.default_rng(20260922)
BETA = _param_rng.normal(0.0, 0.3, size=(K, P))          # outcome linear part
INTERCEPT = np.array([0.0, 0.25, 0.1, 0.35])              # action main effects
THETA = np.vstack([np.zeros(P), _param_rng.normal(0.0, 0.35, size=(K - 1, P))])  # behaviour logits


def make_sigma(corr: str = "indep", rho: float = 0.5, p: int = P) -> np.ndarray:
    if corr == "indep":
        return np.eye(p)
    if corr == "ar1":
        idx = np.arange(p)
        return rho ** np.abs(idx[:, None] - idx[None, :])
    raise ValueError(corr)


# Outcome regression  mu_a(x)
def shared_nonlinear(X: np.ndarray) -> np.ndarray:
    return 0.5 * np.sin(X[:, 0]) + 0.25 * X[:, 1] * X[:, 2]


def action_specific(X: np.ndarray) -> np.ndarray:
    """n x K matrix of action-specific nonlinear terms h_a(x)."""
    h = np.empty((X.shape[0], K))
    h[:, 0] = 0.8 * np.cos(X[:, 3])
    h[:, 1] = 0.4 * (X[:, 4] ** 2 - 1.0)
    h[:, 2] = 0.8 * np.tanh(X[:, 5] * X[:, 6])
    h[:, 3] = 0.6 * (np.abs(X[:, 7]) - 0.8)
    return h


def mu_all(X: np.ndarray) -> np.ndarray:
    """True mean reward for every action: n x K."""
    return INTERCEPT[None, :] + X @ BETA.T + shared_nonlinear(X)[:, None] + action_specific(X)


# Behaviour policy
def behavior_logits(X: np.ndarray, scale: float = 1.0) -> np.ndarray:
    g = X @ THETA.T
    g[:, 1] += 0.8 * X[:, 0] * X[:, 1]
    g[:, 2] += 0.6 * (X[:, 2] ** 2 - 1.0)
    g[:, 3] += 0.8 * np.sin(2.0 * X[:, 8])
    return scale * g


def softmax(z: np.ndarray) -> np.ndarray:
    z = z - z.max(axis=1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=1, keepdims=True)


def behavior_probs(X: np.ndarray) -> np.ndarray:
    return softmax(behavior_logits(X))


# Noise laws
def draw_noise(rng: np.random.Generator, n: int, law: str, **kw) -> tuple[np.ndarray, np.ndarray]:
    """Return (eps, is_outlier_flag)."""
    flag = np.zeros(n, dtype=bool)
    if law == "gauss":
        eps = rng.normal(0.0, 1.0, n)
    elif law == "t3":
        eps = rng.standard_t(3, n)
    elif law == "t2":
        eps = rng.standard_t(2, n)
    elif law == "contam":
        rate = kw.get("rate", 0.05)
        s_out = kw.get("sigma_out", 10.0)
        flag = rng.random(n) < rate
        eps = rng.normal(0.0, 1.0, n)
        eps[flag] = rng.normal(0.0, s_out, flag.sum())
    elif law == "gross":
        # sparse gross outliers: symmetric +/- U(lo, hi) spikes on top of N(0,1)
        rate = kw.get("rate", 0.02)
        lo, hi = kw.get("lo", 20.0), kw.get("hi", 40.0)
        flag = rng.random(n) < rate
        eps = rng.normal(0.0, 1.0, n)
        sgn = rng.choice([-1.0, 1.0], size=flag.sum())
        eps[flag] += sgn * rng.uniform(lo, hi, flag.sum())
    elif law == "gross_pos":
        # ONE-SIDED gross outliers (e.g. reward-hacking spikes); estimand = clean value
        rate = kw.get("rate", 0.02)
        lo, hi = kw.get("lo", 20.0), kw.get("hi", 40.0)
        flag = rng.random(n) < rate
        eps = rng.normal(0.0, 1.0, n)
        eps[flag] += rng.uniform(lo, hi, flag.sum())
    else:
        raise ValueError(law)
    return eps, flag


@dataclass
class ReplayData:
    X: np.ndarray
    A: np.ndarray
    Y: np.ndarray
    pb: np.ndarray          # TRUE behaviour probabilities (n x K) at recorded X
    mu: np.ndarray          # TRUE mean rewards (n x K) at recorded X
    outlier: np.ndarray     # flag for contaminated rows
    meta: dict = field(default_factory=dict)


def generate_replay(rng: np.random.Generator, n: int, noise: str = "gauss",
                    corr: str = "indep", leverage_rate: float = 0.0,
                    leverage_scale: float = 3.0, logging: str = "iid", batches: int = 5,
                    gamma: float = 2.0, hgamma: float = 0.0, **noise_kw) -> ReplayData:
    if logging == "batched":
        return generate_adaptive_replay(rng, n, noise=noise, corr=corr, batches=batches,
                                        gamma=gamma, **noise_kw)
    Sigma = make_sigma(corr)
    L = np.linalg.cholesky(Sigma)
    X = rng.standard_normal((n, P)) @ L.T
    lev = np.zeros(n, dtype=bool)
    if leverage_rate > 0:
        lev = rng.random(n) < leverage_rate
        X[lev] *= leverage_scale  # high-leverage anomalous contexts
    # hgamma > 0 makes the LOGGER partly exploit the nonlinear action-specific reward
    # terms h_a(x) (target policies are unchanged, so true values are unchanged).  A propensity
    # model without h-features is then misspecified in exactly the directions where a linear
    # reward model is wrong -> genuinely damaging double misspecification (regime D).
    pb = behavior_probs(X) if hgamma == 0 else softmax(behavior_logits(X) + hgamma * action_specific(X))
    u = rng.random(n)
    A = (u[:, None] > np.cumsum(pb, axis=1)).sum(axis=1)
    A = np.minimum(A, K - 1)
    mu = mu_all(X)
    eps, flag = draw_noise(rng, n, noise, **noise_kw)
    Y = mu[np.arange(n), A] + eps
    return ReplayData(X=X, A=A, Y=Y, pb=pb, mu=mu, outlier=flag | lev,
                      meta=dict(noise=noise, corr=corr, leverage_rate=leverage_rate, **noise_kw))


def generate_adaptive_replay(rng: np.random.Generator, n: int, noise: str = "gauss",
                             corr: str = "indep", batches: int = 5, gamma: float = 2.0,
                             ridge: float = 1.0, **noise_kw) -> ReplayData:
    """Batched ADAPTIVE logging (non-IID replay history).

    Batch 1 is logged with the base behaviour policy pi_b = softmax(g).  After each
    batch the logger fits a naive per-action ridge-linear reward model qhat_a(x) on
    ALL data observed so far (least squares, not robust - like a simple RSI
    system) and logs the next batch with
        pi_{b,t}(a | x) = softmax_a( g_a(x) + gamma * qhat_a(x) ),
    i.e. it becomes greedier toward actions that looked good.  The logged
    probabilities pi_{b,t}(A_t | X_t) are KNOWN and returned in `pb`, so
    importance weights can use them exactly.  Contexts are IID; actions depend
    on the past through qhat (a martingale-type design).
    """
    Sigma = make_sigma(corr)
    L = np.linalg.cholesky(Sigma)
    X = rng.standard_normal((n, P)) @ L.T
    eps, flag = draw_noise(rng, n, noise, **noise_kw)
    mu = mu_all(X)
    A = np.zeros(n, dtype=int)
    pb = np.zeros((n, K))
    Y = np.zeros(n)
    bounds = np.linspace(0, n, batches + 1).astype(int)
    q_coef = None
    batch_id = np.zeros(n, dtype=int)
    for b in range(batches):
        lo, hi = bounds[b], bounds[b + 1]
        Xb = X[lo:hi]
        logits = behavior_logits(Xb)
        if q_coef is not None:
            X1 = np.column_stack([np.ones(len(Xb)), Xb])
            logits = logits + gamma * (X1 @ q_coef.T)
        p = softmax(logits)
        u = rng.random(hi - lo)
        a = np.minimum((u[:, None] > np.cumsum(p, axis=1)).sum(axis=1), K - 1)
        A[lo:hi], pb[lo:hi], batch_id[lo:hi] = a, p, b
        Y[lo:hi] = mu[np.arange(lo, hi), a] + eps[lo:hi]
        # logger update on all history so far
        Xh = np.column_stack([np.ones(hi), X[:hi]])
        coefs = []
        for k in range(K):
            idx = A[:hi] == k
            if idx.sum() < P + 2:
                coefs.append(np.zeros(P + 1)); continue
            Z = Xh[idx]
            coefs.append(np.linalg.solve(Z.T @ Z + ridge * np.eye(P + 1), Z.T @ Y[:hi][idx]))
        q_coef = np.array(coefs)
    return ReplayData(X=X, A=A, Y=Y, pb=pb, mu=mu, outlier=flag,
                      meta=dict(noise=noise, corr=corr, logging="batched", batches=batches,
                                gamma=gamma, batch_id=batch_id, **noise_kw))


# Ground truth by large Monte Carlo
def true_value(policy_fn, corr: str = "indep", n_mc: int = 2_000_000, seed: int = 999,
               chunk: int = 250_000, return_diag: bool = False):
    """V(pi) = E[sum_a pi(a|X) mu_a(X)] over clean X, with MC standard error.

    If return_diag, also return E[w^2] of the importance weight under pi_b
    (normalised ESS = 1 / E[w^2]) and the 99.9% quantile of w.
    """
    rng = np.random.default_rng(seed)
    L = np.linalg.cholesky(make_sigma(corr))
    s1 = s2 = 0.0
    w2 = 0.0
    wq = []
    m = 0
    while m < n_mc:
        b = min(chunk, n_mc - m)
        X = rng.standard_normal((b, P)) @ L.T
        pi = policy_fn(X)
        v = (pi * mu_all(X)).sum(axis=1)
        s1 += v.sum(); s2 += (v ** 2).sum()
        if return_diag:
            pb = behavior_probs(X)
            # E_{pi_b}[w^2] = E_X sum_a pi^2/pb
            w2 += (pi ** 2 / pb).sum(axis=1).sum()
            u = rng.random(b)
            A = np.minimum((u[:, None] > np.cumsum(pb, axis=1)).sum(axis=1), K - 1)
            wq.append((pi[np.arange(b), A] / pb[np.arange(b), A])[:20000])
        m += b
    mean = s1 / n_mc
    se = np.sqrt((s2 / n_mc - mean ** 2) / n_mc)
    if not return_diag:
        return mean, se
    wq = np.concatenate(wq)
    return mean, se, dict(ess_ratio=1.0 / (w2 / n_mc), w_q999=float(np.quantile(wq, 0.999)),
                          w_max_sample=float(wq.max()))
